version: '3.8'
services:
  postgres:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
